### ISSUE TITLE
Funny demo

### ISSUE THREAD

**Issue by ThiRaBrTNK** [tamble/jquery-ui-daterangepicker#10]
Close button in 'Programmatic Control' is kinda useless: you can't trigger it's click neither clicking it (you are clicking overlay) nor with keyboard (pressing shift+tab also closes drop-down).

**Comment by op16** [comment]
It's true that you aren't actually clicking the Close button, but the overlay. Still, you can trigger it with the keyboard: just use the Open button to open the dropdown, then Tab and Enter will trigger the Close button.

**Comment by ThiRaBrTNK** [comment]
I can't: when I press shift+tab, or tab, drop-down closes immediately, so pressing Enter for triggering button is pointless.

**Comment by ThiRaBrTNK** [comment]
Just tried this in FF and there everything is as you've described, so this is probably Mac Chrome specific.

**Comment by op16** [comment]
Anyway, the Close button was included more for completness than for usefulness.

**Comment by ThiRaBrTNK** [comment]
One more note. This is kinda strange: you can tab from Open button, but can't from input replacement. I guess whole tabbing is somehow broken in Mac Chrome. But this is another issue, so I'll better close this one.

**Comment by op16** [comment]
Tabbing from the input replacement closes the dropdown in FF too.

As a note, using the widget by keyboard only has issues we never took the time to fix. Any such fixes would be most welcomed.
