### ISSUE TITLE
Wrong callback name passed

### ISSUE THREAD

**Issue by ThiRaBrTNK** [tamble/jquery-ui-daterangepicker#11]
you're passing onSelectDay callback to jQuery UI datepicker [here](https://github.com/tamble/jquery-ui-daterangepicker/blob/devel/jquery.comiseo.daterangepicker.js#L205), but there is only [onSelect](http://api.jqueryui.com/datepicker/#option-onSelect).

**Comment by op16** [comment]
Good catch. I think that is the result of some last minute refactoring. I'll release a fix later today.
