### ISSUE TITLE
Ability to change minDate, MaxDate or other datePicker options after initial creation

### ISSUE THREAD

**Issue by seasoup** [tamble/jquery-ui-daterangepicker#16]
I'm using the widget on a single page app that changes between different reports.  We have different date ranges of data for different reports, and I can't find a way to change the minDate and maxDate after the calendar has been created.  Alternatively, if there is a way to update datePicker options after the creation of the daterangepicker, please add documentation to the site that says how.  Thanks, awesome widget.

**Comment by op16** [comment]
Indeed, the widget ignores any options set after initial creation. This feature will be implemented first, in April.
