### ISSUE TITLE
dayNamesMin - doesn't work

### ISSUE THREAD

**Issue by Bear4** [tamble/jquery-ui-daterangepicker#20]
I wanted to change the names of days into another language. 
I tried this:
$("#dayA").daterangepicker({
	dayNamesMin: ["Nd", "Pn", "Wt", "Śr", "Cz", "Pt", "So"],
...
});

The change names aren't display. I have still old names day.
When I change the jQuery-UI library then changes are visible.

Gratulations for good plugin. I like it very much (:

**Comment by op16** [comment]
You need to include the options for the standard datepicker plugin inside `datepickerOptions`.
```javascript
$("#dayA").daterangepicker({
  datepickerOptions: {
    dayNamesMin: ["Nd", "Pn", "Wt", "Śr", "Cz", "Pt", "So"]
  },
...
});
````

**Comment by Bear4** [comment]
Thanks for prompt. 
One detail, the datepickerOptions{} works only on the end code inside daterangepicker({}).
When I set on start, new names aren't visible. 
And when I move datepickerOptions{} on the end it works:
$("#dayA").daterangepicker({
various options,
...
  datepickerOptions: {
    dayNamesMin: ["Nd", "Pn", "Wt", "Śr", "Cz", "Pt", "So"]
  }
});
