### ISSUE TITLE
monthNamesShort - Doesn't Work

### ISSUE THREAD

**Issue by nicclark** [tamble/jquery-ui-daterangepicker#22]
Added to datepickerOptions as so and no adjustment.  Am I missing something?
datepickerOptions : {
     initialText : 'Select By Date...',
     monthNamesShort: [ "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" ],
     numberOfMonths : 1,
     minDate: 0,
     maxDate: 180,					
}

**Comment by op16** [comment]
First, you have given the default value for monthNamesShort, so no changes are to be expected.

Second, contrary to the datepicker documentation, the short form is used only in the month dropdown,
see [this example](http://jqueryui.com/datepicker/#dropdown-month-year).

Also, initialText is not a datepicker option, but a daterangepicker option, so it goes one level up in the options object.

**Comment by nicclark** [comment]
Somehow I missed it only being for the dropdown.   I'll look into other solutions. Thanks

**Comment by nicclark** [comment]
So simple...
datepickerOptions : {
      monthNames: [ "Jan", "Feb", "Mar", "Apr", "Mar", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec" ]
}
