### ISSUE TITLE
Binding dateRangePicker with a knockoutjs viewModel

### ISSUE THREAD

**Issue by pucchur** [tamble/jquery-ui-daterangepicker#23]
Not able to make dateRangePicker read an observable in knockout. I am trying to assign a single date to dateRangePicker http://jsfiddle.net/harsh611/jtj7kemj/12/

**Comment by ghola** [comment]
Are you able to assign a single date to a dateRangePicker outside of an observable?

**Comment by pucchur** [comment]
only using preset ranges but not by just using ranges{start:somedate,end:somedate}

**Comment by ghola** [comment]
You can't use setDate, because such a method is not implemented. You can use setRange though. Take a look at the docs to see how to use it (PrograMmatic Control section).

**Comment by pucchur** [comment]
http://jsfiddle.net/jtj7kemj/13/

**Comment by pucchur** [comment]
what am I doing wrong here?

**Comment by ghola** [comment]
See this: http://jsfiddle.net/bo7msbnq/1/

**Comment by pucchur** [comment]
thanks a million for such great support

**Comment by pucchur** [comment]
http://stackoverflow.com/questions/31288770/knockout-databind-with-jqueryui-based-daterangepicker/31318131#31318131 This is the way to write custom knockoutjs binder for  dateRangePicker, in case it helps some one in the future
