### ISSUE TITLE
minDate

### ISSUE THREAD

**Issue by rajgaurav1** [tamble/jquery-ui-daterangepicker#26]
I want to set the Min date and dates before that should be disabled. I tried 
datepickerOptions: {
         minDate: '2015-07-01',
         maxDate: 'Today'
     }

'Today' is working but minDate is not working

**Comment by op16** [comment]
The datepicker option [minDate](http://api.jqueryui.com/datepicker/#option-minDate) is supposed to be in the format defined by the [dateFormat](http://api.jqueryui.com/datepicker/#option-dateFormat) option, which by default is "mm/dd/yy".

So, minDate: '07/01/2015' works fine, but you might want to include in datepickerOptions `dateFormat: 'yy-mm-dd'` and keep minDate as given. (see http://api.jqueryui.com/datepicker/#utility-formatDate)

**Comment by rajgaurav1** [comment]
i've tried multiple options both in jquery.comiseo.daterangepicker.js file where i changed the date format and the datepickerOptions is tried above... none synced

**Comment by op16** [comment]
Both solutions work for me:

```javascript```
$("#e1").daterangepicker({
    datepickerOptions : {
        dateFormat: 'yy-mm-dd',
        minDate: '2015-07-01',
        maxDate: 'Today'
    }
});
```

```javascript```
$("#e2").daterangepicker({
    datepickerOptions : {
        minDate: '07/01/2015',
        maxDate: 'Today'
    }
});
```

**Comment by rajgaurav1** [comment]
thanks a ton.. the first one worked perfectly
