### ISSUE TITLE
initialText not applying per-initiation.

### ISSUE THREAD

**Issue by jtsternberg** [tamble/jquery-ui-daterangepicker#33]
initialText only works once, and after that, it's not possible to specify different text for each button.

**Comment by op16** [comment]
Sorry, I can't reproduce it, or I didn't understand what you are trying to do.
```javascript
$("#e3").daterangepicker('option', 'initialText', 'Select something');
$("#e3").daterangepicker('option', 'initialText', 'Select something else');
$("#e2").daterangepicker('option', 'initialText', 'Select something else 2');
```

**Comment by op16** [comment]
Please make sure you are not using an outdated version.

**Comment by jtsternberg** [comment]
yep, it was my fault. sorry for raising this issue.
