### ISSUE TITLE
jQuery from v1.9.0 to v1.12.0 incompatibility

### ISSUE THREAD

**Issue by Dr3am3rz** [tamble/jquery-ui-daterangepicker#45]
Hi, I don't know whether is this the right place to ask for help.

I have found your plugin on http://www.jqueryscript.net/ and I realized that I can only use the jQuery core v1.9.0 only.

1) Would you be able to help me on this issue? I am using v1.12.0 for my entire webpage.
2) If I have selected the dates, am I right to say that I have to take the value on the ui-button-text span class?

Thanks for your help in advance! =)

Looking forward to hear from you soon.

**Comment by jriesen** [comment]
FYI, I just got it working fine with jQuery 1.12.1, and I've had no issues so far.  I didn't have to do anything to the code, either... it should just work fine with the latest version of jQuery 1.x, and quite probably jQuery 2.x.

**Comment by glazaga** [comment]
Hi, you know what the solution is? 
Do not initialize with jquery v1.9.1
Error in: jquery.comiseo.daterangepicker.js line: 700
Error: Uncaught ReferenceError: jQuery is not defined
