### ISSUE TITLE
Select month/day range?

### ISSUE THREAD

**Issue by ggallen** [tamble/jquery-ui-daterangepicker#61]
Is there a way to hide the year and select a period based only on month and day? For example, June 1st to August 4th or December 26th to February 7th? That's what I would like to do....

**Comment by op16** [comment]
This issue regards [the datepicker widget](http://jqueryui.com/datepicker/). Should such an option to hide the year exist, you would just pass it on in `datepickerOptions`.

Closed as not applicable.
