### ISSUE TITLE
default selected range

### ISSUE THREAD

**Issue by MiloZ** [tamble/jquery-ui-daterangepicker#7]
Hi,

Is it possible to have a range selected on load, for instance have "month to date" displayed when the page is loaded? 

Thanks

**Comment by op16** [comment]
Hi,

There is no option at the moment to simply select one of the preset ranges (it would be nice to have though).

But there are two posible solutions:

1. use the `setRange` method:
```javascript
$("#yourId").daterangepicker("setRange", {start: moment().startOf('month').startOf('day').toDate(), end: moment().startOf('day').toDate()});
```
2. on the server-side, set the value of original input element to the desired range:
`<input id='yourId' value='{"start":"2015-02-01","end":"2015-02-19"}'>`
(it needs proper html quoting, but you got the ideea)

**Comment by MiloZ** [comment]
Thank you!

**Comment by douglasg14b** [comment]
This kinda of behavior is definitely needed for default options. It's kinda klunky to have to write it into the html. Even more so when you have a page populated by a GET request with a date range.
