### ISSUE TITLE
No future date next arrow

### ISSUE THREAD

**Issue by theeedannyd** [tamble/jquery-ui-daterangepicker#74]
Hi,

I cant seem to select future dates. The arrow disappears when I am shown todays month in the far right date picker.

I have tried setting max dates etc in datepickerOptions.

What am I doing wrong exactly?

    $("#txt-date-range-picker").daterangepicker({
        datepickerOptions: {
            numberOfMonths: 2,
            initialText: 'Select date range...',
            datepickerOptions: {
                minDate: 0,
                maxDate: null
            }
        }
    });

**Comment by op16** [comment]
1. You specified `datepickerOptions` twice. The second (nested) occurrence is ignored.
2. `initialText` is not a date picker option, but daterangepicker option, so it should go one level up.
See http://tamble.github.io/jquery-ui-daterangepicker/#options

**Comment by theeedannyd** [comment]
My humble apologies, I did not notice that. Thanks for your help
