### ISSUE TITLE
Is it possible to customize the formatting of the month and year on the calendar element?

### ISSUE THREAD

**Issue by hdd113** [tamble/jquery-ui-daterangepicker#84]
Standard date formatting in Asian languages are usually YYYY MM.
While I can change for output format, it doesn't seem possible to format the month and date on the calendar element, `(.caption > .month-name)
`
Is it possible? or is the function not implemented yet?

**Comment by op16** [comment]
Our project doesn't use any of the mentioned classes, nor does jQuery UI Datepicker. I suppose you were looking for a different project...

**Comment by hdd113** [comment]
After looking at the release files, that actually seems like the case. Sorry.
